services:
  nginx:
    image: nginx:1.25.4
    container_name: crab-nginx
    depends_on:
      - ui
    env_file:
      - ./.env
    ports:
      - ${CRAB_EXTERNAL_PORT}:80
    networks:
      - private
      - public
    volumes:
      - ./templates/nginx.conf:/etc/nginx/conf.d/revproxy.conf
      - ./config/nginx/well-known:/var/www/html/well-known

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: crab-minio
    entrypoint: ["/bin/sh", "-ce", "/usr/bin/docker-entrypoint.sh minio server --console-address \":9001\" /data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 9001:9001
      - 9000:9000
    env_file:
      - ./.env
    networks:
      - private
      - public
    volumes:
      - minio:/data


  rabbitmq:
    image: rabbitmq:4.0.5
    container_name: crab-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
    env_file:
      - ./.env
    networks:
      - private

  couchdb:
    image: couchdb:3.4.2
    container_name: crab-couchdb
    ports:
      - 5984:5984
    networks:
      - private
      - public
    volumes:
      - couchdb:/opt/couchdb/data
      - ./config/couchdb:/opt/couchdb/etc/local.d

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: crab-keycloak
    ports:
      - 7080:7080
    env_file:
      - ./.env
    networks:
      - private
      - public
    volumes:
      - keycloak:/opt/keycloak/data/
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]

  ui:
    image: crab/ui
    container_name: crab-ui
    depends_on:
      - minio
      - keycloak
    entrypoint: ["gunicorn", "-w", "${GUNICORN_WORKERS}", "main:app", "-b", "0.0.0.0:8957"]
    env_file:
      - ./.env
    networks:
      - private

networks:
  public:
    external: true
    driver: bridge
  private:
    external: false

volumes:
  minio:
  couchdb:
  keycloak:
