#!/bin/bash

CB_EXTERNAL_HOST=$(hostname -f)
CB_EXTERNAL_HTTP_PORT=8080
CB_DEPLOYMENT_PREFIX=chumbucket-
CB_DATA_DIR=/var/chumbucket/data

MINIO_ROOT_USER=root
MINIO_ROOT_PASSWORD=$(head -c 32 /dev/urandom | base64)

cat > .env << EOF
CB_EXTERNAL_HOST=$CB_EXTERNAL_HOST
CB_EXTERNAL_HTTP_PORT=$CB_EXTERNAL_HTTP_PORT
CB_DEPLOYMENT_PREFIX=$CB_DEPLOYMENT_PREFIX
CB_DATA_DIR=$CB_DATA_DIR

GUNICORN_WORKERS=8

MINIO_ROOT_USER=$MINIO_ROOT_USER
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
MINIO_BROWSER_REDIRECT_URL=http://${CB_EXTERNAL_HOST}:9001/


EOF

echo "Minio root user password: $MINIO_ROOT_PASSWORD"
